version: '3.1'
services:

  application:
    image: php:5.6-apache
    restart: always
    volumes:
      - ./:/var/www
      - /etc/letsencrypt:/opt
    ports:
      - 80:80
    links:
      - mysql:mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: vE3aL9YExPatfd3xhEe7e3wR
      DB_NAME: phonebook

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: phonebook
      MYSQL_ROOT_PASSWORD: vE3aL9YExPatfd3xhEe7e3wR

  phpmyadmin:
    image: dyutiman/phpmyadmin:5.0
    stdin_open: true
    tty: true
    links:
      - mysql:mysql
    ports:
      - 9080:80
    restart: always