version: '3.1'
services:

  wordpress:
    image: php:5.6-apache
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - 80:80
      - 443:443
    links:
      - mysql:mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: vE3aL9YExPatfd3xhEe7e3wR
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: vE3aL9YExPatfd3xhEe7e3wR

  phpmyadmin:
    image: dyutiman/phpmyadmin:5.0
    stdin_open: true
    tty: true
    links:
      - mysql:mysql
    ports:
      - 9080:80
    restart: always